### ISSUE TITLE
docker run --rm -it --privileged slamcore-ros2 closes with error message on Jetson Nano

### ISSUE THREAD

**Issue by edrethardo** [slamcore/slamcore-ros2-docker#1]
we followed the build instructions and built the image **on the same device the node will run** 
We are using the most recent Jetpack (4.6.1-b110) and "Slamcore ROS2 Wrapper" (21.06.19)
we tried redownloading and rebuilding the Docker image but still get the same error message as shown below

```
comnovo@slamcore-nano:~$ sudo docker run -it slamcore-ros2
[INFO] [launch]: All log files can be found below /root/.ros/log/2022-03-15-10-32-26-125071-0d1a0c52a5e1-1
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=TypeError("Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)")>
Traceback (most recent call last):
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
await self.__process_event(next_event)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
visit_all_entities_and_collect_futures(entity, self.__context))
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
[Previous line repeated 2 more times]
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
sub_entities = entity.visit(context)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
return self.execute(context)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/load_composable_nodes.py", line 209, in execute
load_node_requests = [
File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/load_composable_nodes.py", line 210, in <listcomp>
get_composable_node_load_request(node_description, context)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/load_composable_nodes.py", line 265, in get_composable_node_load_request
context, evaluate_parameters(
File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 160, in evaluate_parameters
output_params.append(evaluate_parameter_dict(context, param))
File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 95, in evaluate_parameter_dict
raise TypeError(
TypeError: Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)
[INFO] [component_container-1]: process started with pid [41]
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=AttributeError("'NoneType' object has no attribute 'complete'")>
Traceback (most recent call last):
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
await self.__process_event(next_event)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
visit_all_entities_and_collect_futures(entity, self.__context))
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
sub_entities = entity.visit(context)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
return self.execute(context)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/opaque_function.py", line 75, in execute
return self.__function(context, *self.__args, **self.__kwargs)
File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 444, in __on_signal_process_event
if self._subprocess_protocol.complete.done():
AttributeError: 'NoneType' object has no attribute 'complete'
[ERROR] [component_container-1]: process[component_container-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [component_container-1]: sending signal 'SIGTERM' to process[component_container-1]
[ERROR] [component_container-1]: process has died [pid 41, exit code -15, cmd '/opt/ros/foxy/lib/rclcpp_components/component_container --ros-args -r __node:=slamcore_container -r __ns:=/slamcore'].

```

**Comment by bergercookie** [comment]
Hi @edrethardo,

This is due to a bug in the latest version of ROS2 that's available in the ubuntu ppa. Empty default arguments used to work before the said version.

See the following for more details:

* https://github.com/ros2/launch_ros/pull/289/commits/9e609e76ece2684597296d8275dac9be24ed3690

This was fixed in a recent PR, https://github.com/ros2/launch_ros/pull/300/files, but it seems that it's not yet been published in the PPA.

Until this fix  trickles down to the PPA,  edit our launch script(s)  and wrap any empty strings in `Arg` declarations like this:

```python
# instead of:
self.dataset_path = Arg("dataset_path", "", "Path to dataset to run")
                                        ^^ Fail, picked up as NoneType
# use this:
self.dataset_path = Arg("dataset_path", '""', "Path to dataset to run")
                                        ^^^^ OK, picked up as empty string
 ```
 
Notice that the launchfile(s) are included in the debian package which is installed in the container on `docker-build` so you have two options:
 
* Unpack the downloaded `.deb` package, extract all its contents, make your change and re-pack it. Then continue with `docker build...` as per instructions of this repo. This procedure looks like this:
 
   ```sh
   # extract
   dpkg-deb --raw-extract ros-foxy-slamcore-ros_21.06.19-focal1_amd64 ros-foxy-slamcore-ros_21.06.19-focal1_amd64.deb
   cd ros-foxy-slamcore-ros_21.06.19-focal1_amd64
   # make necessary changes
   vim opt/ros/foxy/share/slamcore_slam/launch//slam_publisher.launch.py
   ...
   # build package again
   dpkg-deb --build ros-foxy-slamcore-ros_21.06.19-focal1_amd64
   
   # re-build container and re-run as per instructions
   docker build ...
   docker run ...
   ```
 
* Set the `SLAMCORE_MODE` to `BASH`,  i.e., `docker run -it --rm --privileged --env SLAMCORE_MODE=BASH slamcore-ros2`. This way you'll get an interactive console inside the running container and you should be able to manually edit the launch file. You can find it under `/opt/ros/foxy/share/slamcore_slam/launch/`. After this change, you should be able to run `ros2 launch` inside the container usual. Note that in this scenario this change will not persist a stop of the docker container.

I'll close this issue.
Let's continue the discussion on zendesk if the proposed fix doesn't work for you.
